services:
  web:
    build:
      context: .
      target: dev
    command: yarn dev:docker
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - /app/data
